services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "max_connections=200"
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/app/.env
    environment:
      - BACKEND_CORS_ORIGINS=http://localhost:3000
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    restart: unless-stopped
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - ./bot/.env
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  db_data:
